mod class_filter;
mod heuristics;
mod school_schedule;
mod simulation;
mod simulation_options;
mod stats_tracker;
mod week_calendar;

pub use class_filter::ClassFilter;
pub use school_schedule::class_calendar::ClassCalendar;
pub use school_schedule::class_calendar::ClassKey;
pub use school_schedule::simulation_types::ProfessorKey;
pub use school_schedule::Availability;
pub use school_schedule::ClassMetadata;
pub use school_schedule::Classroom;
pub use school_schedule::ClassroomType;
pub use school_schedule::Group;
pub use school_schedule::Professor;
pub use school_schedule::ProfessorMetadata;
pub use school_schedule::SchoolSchedule;
pub use school_schedule::Semester;
pub use simulation::generate_schedule;
pub use simulation::SimulationOutput;
pub use simulation::SimulationRunReport;
pub use simulation_options::AdvancedSimulationOptions;
pub use simulation_options::LiveUpdate;
pub use simulation_options::ProgressOption;
pub use simulation_options::SimulationOptions;
pub use simulation_options::StopCondition;
pub use simulation_options::TemperatureFunction;
pub use slotmap;
pub use strum;
pub use week_calendar::Day;
pub use week_calendar::Timeslot;
pub use week_calendar::DAY_COUNT;
pub use week_calendar::TIMESLOT_COUNT;

pub use week_calendar::TIMESLOT_08_00;
pub use week_calendar::TIMESLOT_09_00;
pub use week_calendar::TIMESLOT_10_00;
pub use week_calendar::TIMESLOT_11_00;
pub use week_calendar::TIMESLOT_12_00;
pub use week_calendar::TIMESLOT_13_00;
pub use week_calendar::TIMESLOT_14_00;
pub use week_calendar::TIMESLOT_15_00;
pub use week_calendar::TIMESLOT_16_00;
pub use week_calendar::TIMESLOT_17_00;
pub use week_calendar::TIMESLOT_18_00;
pub use week_calendar::TIMESLOT_19_00;
